// @generated by dict-builder — DO NOT EDIT BY HAND.
//
// Prediction data for the Pocket LLM Terminal firmware (RP2040).
// Embedded in flash; `include!`-ed by the firmware, e.g.:
//     mod dict { include!(concat!(env!("OUT_DIR"), "/dict_data.rs")); }
// or with a fixed path:
//     include!("../generated/dict_data.rs");
//
// Format:
//   pub static WORDS: &[&str]
//     Top-N words, sorted by DESCENDING frequency (ties broken alphabetically).
//     Firmware does a prefix scan over this slice to offer word completions.
//
//   pub static BIGRAMS: &[(&str, &[&str])]
//     For common preceding words (the head), their most-likely next words
//     (the followers), already ranked best-first and capped per head.
//     Firmware looks up the last committed word as the head and offers the
//     followers as next-word predictions. Heads are listed in descending
//     frequency order; an empty slice means no bigram data was available.
//
// Counts: 237 words, 0 bigram heads.

pub static WORDS: &[&str] = &[
    "the", "of", "and", "to", "a", "in", "is", "you", 
    "that", "it", "he", "was", "for", "on", "are", "as", 
    "with", "his", "they", "at", "be", "this", "have", "from", 
    "or", "one", "had", "by", "word", "but", "not", "what", 
    "all", "were", "we", "when", "your", "can", "said", "there", 
    "use", "an", "each", "which", "she", "do", "how", "their", 
    "if", "will", "up", "other", "about", "out", "many", "then", 
    "them", "these", "so", "some", "her", "would", "make", "like", 
    "him", "into", "time", "has", "look", "two", "more", "write", 
    "see", "number", "way", "could", "people", "than", "first", "been", 
    "call", "who", "now", "find", "long", "down", "day", "did", 
    "get", "come", "made", "may", "part", "over", "new", "sound", 
    "take", "only", "little", "work", "know", "place", "year", "live", 
    "back", "give", "most", "very", "after", "thing", "our", "name", 
    "good", "sentence", "think", "say", "great", "where", "help", "through", 
    "much", "before", "line", "right", "too", "mean", "old", "any", 
    "same", "tell", "boy", "follow", "came", "want", "show", "also", 
    "around", "form", "three", "small", "set", "put", "end", "does", 
    "another", "well", "large", "must", "big", "even", "such", "because", 
    "turn", "here", "why", "ask", "went", "men", "read", "need", 
    "land", "different", "home", "us", "move", "try", "kind", "hand", 
    "picture", "again", "change", "play", "spell", "air", "away", "animal", 
    "house", "point", "page", "letter", "mother", "answer", "found", "study", 
    "still", "learn", "should", "world", "hello", "hi", "hey", "yes", 
    "no", "okay", "thanks", "please", "sorry", "sure", "maybe", "today", 
    "tomorrow", "tonight", "morning", "night", "week", "month", "weather", "email", 
    "phone", "message", "question", "explain", "summary", "summarize", "translate", "rewrite", 
    "example", "simple", "quick", "clear", "send", "reply", "sprig", "code", 
    "build", "test", "start", "stop", "open", "close", "list", "screen", 
    "button", "battery", "wifi", "power", "press", 
];

pub static BIGRAMS: &[(&str, &[&str])] = &[
];
