//! Sprig Pocket LLM Terminal — Milestone 1 firmware entry point.
//!
//! Boots the RP2040, brings up the ST7735 LCD, configures the eight buttons,
//! and runs the twin-pad keyboard from `sprig-llm-core`, redrawing the screen
//! whenever the keyboard reports a visible change.
//!
//! Milestone 1 deliberately stops at on-device text composition: `Send` and
//! `Expand` outcomes only flash a status banner. WiFi/TLS and the actual LLM
//! request/stream land in Milestone 2.
//!
//! Architecture:
//!   * [`input`]  — debounced GPIO scanning → `KeyEvent`s.
//!   * [`display`] — ST7735 driver + four-zone embedded-graphics renderer.
//!   * [`pins`]   — the verified Sprig pinout.
//!   * core crate — the `Keyboard` state machine + `Predictor`.

#![no_std]
#![no_main]

#[allow(dead_code)] // BIGRAMS is reserved for next-word ranking (not used yet)
mod dict_data; // generated by tools/dict-builder from assets/words.txt
mod config; // copy config.example.rs -> config.rs and fill in (gitignored)
mod display;
mod input;
mod net;
mod pins;

use defmt::info;
use embassy_executor::Spawner;
use embassy_rp::gpio::{AnyPin, Level, Output, Pin};
use embassy_rp::spi::{self, Spi};
use embassy_time::{Delay, Duration, Timer};
use embedded_hal_bus::spi::ExclusiveDevice;
use st7735_lcd::{Orientation, ST7735};

use sprig_llm_core::keyboard::{Keyboard, Outcome};
use sprig_llm_core::predict::StaticPredictor;

use crate::display::Ui;
use crate::input::Buttons;
use crate::net::{Net, NetPins};

use core::fmt::Write as _;
use heapless::String as HString;

/// Instruction prefix prepended to the draft for an Expand request, per spec.
const EXPAND_PREFIX: &str =
    "Rewrite this as a clear, complete prompt; output only the rewritten prompt:\n";

/// Capacity for the accumulated, on-screen LLM response. The response view only
/// renders the visible tail, so this just bounds total retained text.
const RESPONSE_CAP: usize = 2048;

/// Max prompt length: the 256-char draft plus the Expand instruction prefix.
const PROMPT_CAP: usize = 512;

// Pull in the RTT logger transport and the defmt panic handler. These are only
// linked for their side effects.
use defmt_rtt as _;
use panic_probe as _;

/// SPI clock for the ST7735. The panel is comfortable well past this; 32 MHz is
/// a safe, fast default for a short PCB trace.
const SPI_HZ: u32 = 32_000_000;

#[embassy_executor::main]
async fn main(spawner: Spawner) {
    // Bring up clocks, power, and the GPIO/peripheral singletons.
    let p = embassy_rp::init(Default::default());
    info!("sprig-llm-firmware: boot (Milestone 2)");

    // --- Display SPI bus (SPI0: SCK=18, MOSI=19, MISO=16). ---
    // The pin *constants* in `pins` document the wiring; the embassy `p.PIN_xx`
    // singletons below must match those numbers.
    let mut spi_cfg = spi::Config::default();
    spi_cfg.frequency = SPI_HZ;
    let spi = Spi::new_blocking(
        p.SPI0,
        p.PIN_18, // SCK   (pins::display::SCK)
        p.PIN_19, // MOSI  (pins::display::MOSI)
        p.PIN_16, // MISO  (pins::display::MISO, unused by the panel)
        spi_cfg,
    );

    // Control lines for the ST7735.
    let dc = Output::new(p.PIN_22, Level::Low); // pins::display::DC
    let rst = Output::new(p.PIN_26, Level::Low); // pins::display::RST
    let cs = Output::new(p.PIN_20, Level::High); // pins::display::CS (idle high)
    // Backlight on.
    let _backlight = Output::new(p.PIN_17, Level::High); // pins::display::BACKLIGHT

    // `st7735-lcd` 0.10 wants an embedded-hal `SpiDevice` (CS managed per
    // transaction). Wrap our raw blocking bus + CS pin in an ExclusiveDevice.
    // It is `.unwrap()`-free: ExclusiveDevice::new only fails if CS can't be set
    // idle, which an infallible RP2040 output never does — use `new_no_delay`
    // since the ST7735 driver inserts its own timing.
    let mut delay = Delay;
    let spi_dev = ExclusiveDevice::new_no_delay(spi, cs)
        .expect("CS pin is infallible");

    // ST7735: RGB order true, not color-inverted, 160x128.
    let mut lcd = ST7735::new(spi_dev, dc, rst, true, false, display::WIDTH, display::HEIGHT);
    // `init`/`set_orientation` return Err(()) on bus error; on a soldered panel
    // this should not fail. We surface it via defmt and keep going so the input
    // path is still exercised on the bench.
    if lcd.init(&mut delay).is_err() {
        defmt::error!("ST7735 init failed");
    }
    if lcd.set_orientation(&Orientation::Landscape).is_err() {
        defmt::error!("ST7735 set_orientation failed");
    }

    if Ui::clear(&mut lcd).is_err() {
        defmt::error!("display clear failed");
    }

    // --- Buttons (W=5 A=6 S=7 D=8 I=12 J=13 K=14 L=15), in input::SCAN_ORDER. ---
    let raw: [AnyPin; 8] = [
        p.PIN_5.degrade(),  // W
        p.PIN_6.degrade(),  // A
        p.PIN_7.degrade(),  // S
        p.PIN_8.degrade(),  // D
        p.PIN_12.degrade(), // I
        p.PIN_13.degrade(), // J
        p.PIN_14.degrade(), // K
        p.PIN_15.degrade(), // L
    ];
    let mut buttons = Buttons::new(input::configure(raw));

    // --- WiFi + network stack bring-up (Milestone 2). ---
    // The CYW43439 uses the Pico W's standard internal wiring (PWR=23, CS=25,
    // PIO-SPI DIO=24, CLK=29), which does NOT conflict with the Sprig's display
    // or button pins. `net::init` joins WiFi and waits for DHCP, so show a
    // splash first; it blocks here until connected (retrying on failure).
    let _ = Ui::response(&mut lcd, "Connecting WiFi...", "Joining network and getting DHCP lease.");
    // `init` retries the WiFi join forever, so a returned `Err` is not expected;
    // treat it as fatal (the splash already told the user we're connecting).
    let mut net: Net = net::init(
        spawner,
        NetPins {
            pwr: p.PIN_23,
            cs: p.PIN_25,
            dio: p.PIN_24,
            clk: p.PIN_29,
            pio: p.PIO0,
            dma: p.DMA_CH0,
        },
    )
    .await
    .unwrap_or_else(|()| panic!("network init failed"));

    // --- Core keyboard + predictor. ---
    let predictor = StaticPredictor::new(dict_data::WORDS);
    let mut kb = Keyboard::new();
    let mut status: display::Status = display::Status::new();

    // Initial paint.
    let _ = Ui::render(&mut lcd, &kb, &status);

    // --- Main loop: scan → feed core → redraw on change. ---
    let tick = Duration::from_millis(input::TICK_MS);
    // True while a full-screen LLM response is shown; the next key dismisses it.
    let mut showing_response = false;
    loop {
        // Collect this tick's events first (the closure can't borrow `kb` while
        // `buttons` is borrowed), then process them.
        let mut events: heapless::Vec<sprig_llm_core::button::KeyEvent, 8> =
            heapless::Vec::new();
        buttons.poll(|ev| {
            let _ = events.push(ev);
        });

        // A response view stays on screen until any key is pressed; that key just
        // returns to the keyboard (it is consumed, not typed).
        if showing_response {
            if !events.is_empty() {
                showing_response = false;
                let _ = Ui::render(&mut lcd, &kb, &status);
            }
            Timer::after(tick).await;
            continue;
        }

        let mut dirty = false;
        for ev in events {
            match kb.process(ev, &predictor) {
                Outcome::Idle => {}
                Outcome::Redraw => {
                    status.clear();
                    dirty = true;
                }
                Outcome::Send => {
                    info!("Send requested; draft len={}", kb.text().len());
                    // Stream the reply onto a full-screen response view. The
                    // prompt is the raw draft; after viewing, the next key event
                    // repaints the keyboard.
                    let mut prompt: HString<PROMPT_CAP> = HString::new();
                    let _ = prompt.push_str(kb.text());
                    stream_to_screen(&mut lcd, &mut net, &prompt).await;
                    showing_response = true; // keep the reply up until a key press
                }
                Outcome::Expand => {
                    info!("Expand requested; draft len={}", kb.text().len());
                    // Prepend the rewrite instruction and stream the rewrite onto
                    // the response view. NOTE: the core `Keyboard` exposes no
                    // public draft setter, so we cannot replace the draft buffer
                    // in place; the rewrite is shown full-screen instead.
                    // TODO(M2): add `Keyboard::set_text` to the core crate to let
                    // Expand replace the draft.
                    let mut prompt: HString<PROMPT_CAP> = HString::new();
                    let _ = prompt.push_str(EXPAND_PREFIX);
                    let _ = prompt.push_str(kb.text());
                    stream_to_screen(&mut lcd, &mut net, &prompt).await;
                    showing_response = true;
                }
            }
        }

        if dirty {
            let _ = Ui::render(&mut lcd, &kb, &status);
        }

        Timer::after(tick).await;
    }
}

/// Send `prompt` to the LLM and stream the reply onto the full-screen response
/// view, repainting as each delta arrives. Returns the accumulated reply text.
///
/// Generic over the draw target so it works with the concrete ST7735 without
/// spelling out its (very long) type. The accumulator + the LCD are disjoint
/// from `net`, so the per-delta closure can borrow them while `net` streams.
async fn stream_to_screen<D>(lcd: &mut D, net: &mut Net, prompt: &str) -> HString<RESPONSE_CAP>
where
    D: embedded_graphics::draw_target::DrawTarget<Color = embedded_graphics::pixelcolor::Rgb565>,
{
    let mut acc: HString<RESPONSE_CAP> = HString::new();
    let _ = Ui::response(lcd, "Streaming...", "");
    net.set_led(true).await;

    let result = net
        .send_prompt(prompt, |delta| {
            // Append (dropping overflow) and repaint the tail.
            for ch in delta.chars() {
                if acc.push(ch).is_err() {
                    break;
                }
            }
            let _ = Ui::response(lcd, "Streaming...", &acc);
        })
        .await;

    net.set_led(false).await;

    match result {
        Ok(()) => {
            let _ = Ui::response(lcd, "Done (any key = back)", &acc);
        }
        Err(e) => {
            let mut hdr: HString<32> = HString::new();
            let _ = write!(hdr, "Error: {:?}", e);
            let _ = Ui::response(lcd, &hdr, &acc);
        }
    }
    acc
}
