//! Sprig Pocket LLM Terminal — firmware entry point.
//!
//! Boots the RP2040, brings up the ST7735 LCD and the eight buttons, joins WiFi,
//! and runs the twin-pad keyboard from `sprig-llm-core`. A composed prompt is
//! streamed to an LLM over OpenRouter and the reply is rendered live. The device
//! also does multi-turn chat, an on-device settings menu, quick prompts, AI game
//! modes, response scrolling, a token-usage readout, audio feedback, USB
//! "type-to-PC", and flash-persisted settings + conversation.
//!
//! Modules:
//!   * [`input`]   — debounced GPIO scanning → `KeyEvent`s.
//!   * [`display`] — ST7735 driver + keyboard / response / menu renderer.
//!   * [`net`]     — WiFi bring-up + streaming HTTPS to the LLM.
//!   * [`audio`]   — PIO-I²S key click + reply chime.
//!   * [`usb`]     — USB HID keyboard ("type the reply into a PC").
//!   * [`storage`] — flash persistence of settings + conversation.
//!   * [`pins`]    — the verified Sprig pinout.
//!   * core crate  — the `Keyboard` state machine, `Predictor`, and provider/SSE.

#![no_std]
#![no_main]

#[allow(dead_code)] // BIGRAMS is reserved for next-word ranking (not used yet)
mod dict_data; // generated by tools/dict-builder from assets/words.txt
mod audio;
mod config; // copy config.example.rs -> config.rs and fill in (gitignored)
mod display;
mod input;
mod net;
mod pins;
mod storage;
#[allow(dead_code)] // public API used once the "type to PC" trigger is wired in
mod usb;

use defmt::info;
use embassy_executor::Spawner;
use embassy_rp::gpio::{AnyPin, Level, Output, Pin};
use embassy_rp::spi::{self, Spi};
use embassy_time::{Delay, Duration, Timer};
use embedded_hal_bus::spi::ExclusiveDevice;
use st7735_lcd::{Orientation, ST7735};

use sprig_llm_core::button::{Button, KeyEvent};
use sprig_llm_core::keyboard::{Keyboard, Outcome};
use sprig_llm_core::predict::StaticPredictor;
use sprig_llm_core::provider::Role;

use crate::audio::Audio;
use crate::display::Ui;
use crate::input::Buttons;
use crate::net::{Net, NetError, NetPins};

use core::fmt::Write as _;
use heapless::String as HString;
use heapless::Vec as HVec;

/// Instruction prefix prepended to the draft for an Expand request, per spec.
const EXPAND_PREFIX: &str =
    "Rewrite this as a clear, complete prompt; output only the rewritten prompt:\n";

/// Capacity for the accumulated, on-screen LLM response. The response view only
/// renders the visible tail, so this just bounds total retained text.
const RESPONSE_CAP: usize = 2048;

/// Max prompt length: the 256-char draft plus the Expand instruction prefix.
const PROMPT_CAP: usize = 512;

/// Per-turn stored text capacity in the conversation history.
const TURN_CAP: usize = 256;
/// Maximum number of (role, text) turns kept; oldest dropped when full.
const MAX_TURNS: usize = 6;

/// Selectable models. The first entry is the build-time default `config::MODEL`;
/// the rest are alternates reachable through the same OpenRouter endpoint.
const MODELS: &[&str] = &[
    config::MODEL,
    "deepseek/deepseek-chat",
    "deepseek/deepseek-r1:free",
];

/// Selectable personas: a label plus an optional system prompt (None = default,
/// no system message). Fed to `send_chat` as the `system` argument.
const PERSONAS: &[(&str, Option<&str>)] = &[
    ("Default", None),
    ("Concise", Some("Answer in at most 2 short sentences.")),
    (
        "Coder",
        Some("You are a terse coding assistant; prefer code with minimal prose."),
    ),
    ("Translate", Some("Translate the user's message into English.")),
];

/// Selectable response length caps (max_tokens).
const MAX_TOKENS: &[u32] = &[256, 512, 1024, 2048];

/// One stored conversation turn.
type Turn = (Role, HString<TURN_CAP>);

/// On-device settings: selected indices into the compiled option arrays, plus
/// the live conversation history. Drives every subsequent Send/Expand.
struct Settings {
    model: usize,
    persona: usize,
    max_tokens: usize,
    /// Highlighted menu row (for navigation).
    cursor: usize,
    /// Transient per-session system-prompt override set by starting a game from
    /// the menu. Takes precedence over the persona; NOT persisted to flash.
    system_override: Option<&'static str>,
}

impl Settings {
    const fn new() -> Self {
        Self {
            model: 0,
            persona: 0,
            max_tokens: 2, // default 1024
            cursor: 0,
            system_override: None,
        }
    }

    fn model(&self) -> &'static str {
        MODELS[self.model]
    }
    fn persona(&self) -> Option<&'static str> {
        PERSONAS[self.persona].1
    }
    /// The effective system prompt: a game override if one is active, otherwise
    /// the selected persona. Fed to `send_chat` as the `system` argument.
    fn system(&self) -> Option<&'static str> {
        self.system_override.or_else(|| self.persona())
    }
    fn max_tokens(&self) -> u32 {
        MAX_TOKENS[self.max_tokens]
    }
}

/// The menu rows, in display order. `Back` returns to the keyboard; `NewConv`
/// clears history.
/// One-tap canned prompts: (menu label, text loaded into the draft to edit/send).
const QUICK_PROMPTS: &[(&str, &str)] = &[
    ("Summarize", "Summarize the following:\n"),
    ("Explain (ELI5)", "Explain like I'm 5: "),
    ("Translate -> EN", "Translate to English: "),
    ("Proofread", "Proofread and correct: "),
    ("Brainstorm", "Brainstorm ideas about: "),
];

/// AI game personas: (menu label, system prompt, kickoff draft loaded into the
/// keyboard). Selecting one sets a transient `system_override` and primes the
/// draft so the user just presses Send to begin.
const GAMES: &[(&str, &str, &str)] = &[
    (
        "Play: Adventure",
        "You are the game master of a short interactive text adventure. Keep each reply under 60 words and end with 2-3 numbered choices.",
        "Start the adventure.",
    ),
    (
        "Play: 20 Questions",
        "Let's play 20 Questions. I am thinking of an object; ask me yes/no questions one at a time to guess it, and count your questions.",
        "Let's play.",
    ),
    (
        "Play: Trivia",
        "You are a trivia host. Ask one multiple-choice question at a time (A-D). After my answer, say if I was right and ask the next question.",
        "Start the trivia.",
    ),
];

const ROW_MODEL: usize = 0;
const ROW_PERSONA: usize = 1;
const ROW_TOKENS: usize = 2;
const ROW_NEWCONV: usize = 3;
/// Quick-prompt rows occupy `[QUICK_BASE, QUICK_BASE + QUICK_PROMPTS.len())`.
const QUICK_BASE: usize = 4;
/// Game rows occupy `[GAMES_BASE, GAMES_BASE + GAMES.len())`, after the quick
/// prompts and before Back.
const GAMES_BASE: usize = QUICK_BASE + QUICK_PROMPTS.len();
const ROW_BACK: usize = GAMES_BASE + GAMES.len();
const MENU_ROWS: usize = ROW_BACK + 1;

/// Top-level UI mode.
enum Mode {
    /// Composing on the keyboard.
    Composing,
    /// Showing a finished LLM reply; `usize` is the scroll offset in wrapped rows.
    ShowingResponse(usize),
    /// In the settings menu.
    Settings,
}

// Pull in the RTT logger transport and the defmt panic handler. These are only
// linked for their side effects.
use defmt_rtt as _;
use panic_probe as _;

/// SPI clock for the ST7735. The panel is comfortable well past this; 32 MHz is
/// a safe, fast default for a short PCB trace.
const SPI_HZ: u32 = 32_000_000;

// Audio uses PIO1 (net.rs owns PIO0 for WiFi). Bind PIO1's IRQ0 to the embassy
// PIO interrupt handler so the audio state machine's DMA completes can be
// serviced. DMA_CH0 is taken by WiFi; audio uses DMA_CH1 (passed in `main`).
embassy_rp::bind_interrupts!(struct AudioIrqs {
    PIO1_IRQ_0 => embassy_rp::pio::InterruptHandler<embassy_rp::peripherals::PIO1>;
});

#[embassy_executor::main]
async fn main(spawner: Spawner) {
    // Bring up clocks, power, and the GPIO/peripheral singletons.
    let p = embassy_rp::init(Default::default());
    info!("sprig-llm-firmware: boot (Milestone 2)");

    // --- Display SPI bus (SPI0: SCK=18, MOSI=19, MISO=16). ---
    // The pin *constants* in `pins` document the wiring; the embassy `p.PIN_xx`
    // singletons below must match those numbers.
    let mut spi_cfg = spi::Config::default();
    spi_cfg.frequency = SPI_HZ;
    let spi = Spi::new_blocking(
        p.SPI0,
        p.PIN_18, // SCK   (pins::display::SCK)
        p.PIN_19, // MOSI  (pins::display::MOSI)
        p.PIN_16, // MISO  (pins::display::MISO, unused by the panel)
        spi_cfg,
    );

    // Control lines for the ST7735.
    let dc = Output::new(p.PIN_22, Level::Low); // pins::display::DC
    let rst = Output::new(p.PIN_26, Level::Low); // pins::display::RST
    let cs = Output::new(p.PIN_20, Level::High); // pins::display::CS (idle high)
    // Backlight on.
    let _backlight = Output::new(p.PIN_17, Level::High); // pins::display::BACKLIGHT

    // `st7735-lcd` 0.10 wants an embedded-hal `SpiDevice` (CS managed per
    // transaction). Wrap our raw blocking bus + CS pin in an ExclusiveDevice.
    // It is `.unwrap()`-free: ExclusiveDevice::new only fails if CS can't be set
    // idle, which an infallible RP2040 output never does — use `new_no_delay`
    // since the ST7735 driver inserts its own timing.
    let mut delay = Delay;
    let spi_dev = ExclusiveDevice::new_no_delay(spi, cs)
        .expect("CS pin is infallible");

    // ST7735: RGB order true, not color-inverted, 160x128.
    let mut lcd = ST7735::new(spi_dev, dc, rst, true, false, display::WIDTH, display::HEIGHT);
    // `init`/`set_orientation` return Err(()) on bus error; on a soldered panel
    // this should not fail. We surface it via defmt and keep going so the input
    // path is still exercised on the bench.
    if lcd.init(&mut delay).is_err() {
        defmt::error!("ST7735 init failed");
    }
    if lcd.set_orientation(&Orientation::Landscape).is_err() {
        defmt::error!("ST7735 set_orientation failed");
    }

    if Ui::clear(&mut lcd).is_err() {
        defmt::error!("display clear failed");
    }

    // --- Buttons (W=5 A=6 S=7 D=8 I=12 J=13 K=14 L=15), in input::SCAN_ORDER. ---
    let raw: [AnyPin; 8] = [
        p.PIN_5.degrade(),  // W
        p.PIN_6.degrade(),  // A
        p.PIN_7.degrade(),  // S
        p.PIN_8.degrade(),  // D
        p.PIN_12.degrade(), // I
        p.PIN_13.degrade(), // J
        p.PIN_14.degrade(), // K
        p.PIN_15.degrade(), // L
    ];
    let mut buttons = Buttons::new(input::configure(raw));

    // --- WiFi + network stack bring-up (Milestone 2). ---
    // The CYW43439 uses the Pico W's standard internal wiring (PWR=23, CS=25,
    // PIO-SPI DIO=24, CLK=29), which does NOT conflict with the Sprig's display
    // or button pins. `net::init` joins WiFi and waits for DHCP, so show a
    // splash first; it blocks here until connected (retrying on failure).
    let _ = Ui::response(&mut lcd, "Connecting WiFi...", "Joining network and getting DHCP lease.");
    // `init` retries the WiFi join forever, so a returned `Err` is not expected;
    // treat it as fatal (the splash already told the user we're connecting).
    let mut net: Net = net::init(
        spawner,
        NetPins {
            pwr: p.PIN_23,
            cs: p.PIN_25,
            dio: p.PIN_24,
            clk: p.PIN_29,
            pio: p.PIO0,
            dma: p.DMA_CH0,
        },
    )
    .await
    .unwrap_or_else(|()| panic!("network init failed"));

    // --- Audio (PIO1 + DMA_CH1; PIO0/DMA_CH0 are WiFi's). ---
    let mut audio = Audio::init(
        p.PIO1,
        AudioIrqs,
        p.PIN_9,
        p.PIN_10,
        p.PIN_11,
        p.DMA_CH1,
    );

    // --- USB HID keyboard on the native USB: lets the device type a reply into
    // a connected PC. WiFi uses the separate CYW43 radio, so the two coexist. ---
    let mut usb_kb = usb::init(spawner, p.USB);

    // --- Core keyboard + predictor. ---
    let predictor = StaticPredictor::new(dict_data::WORDS);
    let mut kb = Keyboard::new();
    let mut status: display::Status = display::Status::new();

    // --- Persistent storage (top flash sector). Blocking-mode driver, no DMA
    // needed; reads are plain XIP, erase/write run from RAM in a critical
    // section (see storage.rs). `p.FLASH` is otherwise unused. ---
    let mut flash = storage::Flash::new_blocking(p.FLASH);

    // --- App state: settings + bounded conversation history + UI mode. ---
    let mut settings = Settings::new();
    let mut history: HVec<Turn, MAX_TURNS> = HVec::new();

    // Restore saved settings + conversation, if any. Indices are clamped to the
    // current option arrays so an old/oversized index can never panic.
    if let Some(saved) = storage::load(&mut flash) {
        if (saved.model as usize) < MODELS.len() {
            settings.model = saved.model as usize;
        }
        if (saved.persona as usize) < PERSONAS.len() {
            settings.persona = saved.persona as usize;
        }
        if (saved.max_tokens as usize) < MAX_TOKENS.len() {
            settings.max_tokens = saved.max_tokens as usize;
        }
        for (role_u8, text) in saved.turns {
            // `push_turn` truncates to TURN_CAP and drops oldest when full.
            push_turn(&mut history, storage::role_from_u8(role_u8), &text);
        }
        info!("storage: restored {} turn(s)", history.len());
    }

    let mut mode = Mode::Composing;
    // Holds the most recent finished reply, for scrolling in ShowingResponse.
    let mut last_reply: HString<RESPONSE_CAP> = HString::new();
    // Running total of tokens billed across replies this power-on session.
    let mut session_tokens: u32 = 0;

    // Initial paint.
    let _ = Ui::render(&mut lcd, &kb, &status);

    // --- Main loop: scan → dispatch by mode → redraw on change. ---
    let tick = Duration::from_millis(input::TICK_MS);
    loop {
        // Collect this tick's events first (the closure can't borrow `kb` while
        // `buttons` is borrowed), then process them.
        let mut events: HVec<KeyEvent, 8> = HVec::new();
        buttons.poll(|ev| {
            let _ = events.push(ev);
        });

        match mode {
            // ---------------------------------------------------------------
            // ShowingResponse: W/I scroll up, S/K scroll down, anything else
            // dismisses back to the keyboard.
            // ---------------------------------------------------------------
            Mode::ShowingResponse(mut scroll) => {
                let (total, visible) = Ui::wrapped_row_count(&last_reply);
                let max_scroll = total.saturating_sub(visible);
                let mut dismiss = false;
                let mut moved = false;
                let mut type_pc = false;
                for ev in &events {
                    if let KeyEvent::Tap(b) = ev {
                        match b {
                            Button::W | Button::I => {
                                if scroll > 0 {
                                    scroll -= 1;
                                    moved = true;
                                }
                            }
                            Button::S | Button::K => {
                                if scroll < max_scroll {
                                    scroll += 1;
                                    moved = true;
                                }
                            }
                            // D types the reply into the connected PC over USB.
                            Button::D => type_pc = true,
                            // Any other key dismisses back to the keyboard.
                            _ => dismiss = true,
                        }
                    }
                }
                if dismiss {
                    mode = Mode::Composing;
                    let _ = Ui::render(&mut lcd, &kb, &status);
                } else {
                    if type_pc {
                        let _ = Ui::response_scrolled(&mut lcd, "Typing to PC...", &last_reply, scroll);
                        usb_kb.type_text(&last_reply).await;
                    }
                    if moved || type_pc {
                        let _ = Ui::response_scrolled(
                            &mut lcd,
                            "scroll  D=type  L=back",
                            &last_reply,
                            scroll,
                        );
                    }
                    mode = Mode::ShowingResponse(scroll);
                }
            }

            // ---------------------------------------------------------------
            // Settings: W/I up, S/K down to move; A/L/D to change value; the
            // Back row (or a non-nav key on it) exits.
            // ---------------------------------------------------------------
            Mode::Settings => {
                let mut redraw = false;
                let mut exit = false;
                // Set when a persisted value (a setting index, or history via
                // New conversation) changed, so we flush to flash after the loop.
                let mut save_now = false;
                for ev in &events {
                    if let KeyEvent::Tap(b) = ev {
                        match b {
                            Button::W | Button::I => {
                                settings.cursor =
                                    (settings.cursor + MENU_ROWS - 1) % MENU_ROWS;
                                redraw = true;
                            }
                            Button::S | Button::K => {
                                settings.cursor = (settings.cursor + 1) % MENU_ROWS;
                                redraw = true;
                            }
                            Button::A | Button::L | Button::D => {
                                // Activate / change the highlighted row's value.
                                match settings.cursor {
                                    ROW_MODEL => {
                                        settings.model =
                                            (settings.model + 1) % MODELS.len();
                                        save_now = true;
                                    }
                                    ROW_PERSONA => {
                                        settings.persona =
                                            (settings.persona + 1) % PERSONAS.len();
                                        // Choosing a persona ends any game mode so
                                        // normal chat resumes.
                                        settings.system_override = None;
                                        save_now = true;
                                    }
                                    ROW_TOKENS => {
                                        settings.max_tokens =
                                            (settings.max_tokens + 1) % MAX_TOKENS.len();
                                        save_now = true;
                                    }
                                    ROW_NEWCONV => {
                                        history.clear();
                                        // A fresh conversation also leaves game mode.
                                        settings.system_override = None;
                                        save_now = true;
                                        let _ = audio.play_click().await;
                                    }
                                    ROW_BACK => exit = true,
                                    q if q >= QUICK_BASE && q < GAMES_BASE => {
                                        // Load the canned prompt into the draft and
                                        // return to the keyboard to edit / send it.
                                        kb.set_text(QUICK_PROMPTS[q - QUICK_BASE].1);
                                        exit = true;
                                    }
                                    q if q >= GAMES_BASE && q < ROW_BACK => {
                                        // Start a game: set the transient system
                                        // override, clear history, prime the draft
                                        // with the kickoff line, and exit to the
                                        // keyboard so the user just presses Send.
                                        let (_, sys, kick) = GAMES[q - GAMES_BASE];
                                        settings.system_override = Some(sys);
                                        history.clear();
                                        kb.set_text(kick);
                                        save_now = true;
                                        exit = true;
                                    }
                                    _ => {}
                                }
                                redraw = true;
                            }
                            _ => {}
                        }
                    }
                }
                // Persist the changed setting / cleared history. The menu is a
                // quiescent point (no network request in flight), so the brief
                // flash write is safe here.
                if save_now {
                    persist(&mut flash, &settings, &history);
                }
                if exit {
                    mode = Mode::Composing;
                    let _ = Ui::render(&mut lcd, &kb, &status);
                } else if redraw {
                    draw_menu(&mut lcd, &settings, &history);
                }
            }

            // ---------------------------------------------------------------
            // Composing: feed events to the core keyboard.
            // ---------------------------------------------------------------
            Mode::Composing => {
                let mut dirty = false;
                for ev in events {
                    match kb.process(ev, &predictor) {
                        Outcome::Idle => {}
                        Outcome::Redraw => {
                            status.clear();
                            dirty = true;
                        }
                        Outcome::Settings => {
                            settings.cursor = 0;
                            mode = Mode::Settings;
                            draw_menu(&mut lcd, &settings, &history);
                            break; // stop feeding queued events to the hidden keyboard
                        }
                        Outcome::Send => {
                            info!("Send requested; draft len={}", kb.text().len());
                            // Push the user turn, stream the multi-turn reply, then
                            // store the assistant turn (truncated). The reply stays
                            // up (scrollable) until a key dismisses it.
                            push_turn(&mut history, Role::User, kb.text());
                            let reply = stream_chat_to_screen(
                                &mut lcd, &mut net, &settings, &history,
                                &mut session_tokens,
                            )
                            .await;
                            last_reply.clear();
                            match reply {
                                Ok(r) => {
                                    push_turn(&mut history, Role::Assistant, &r);
                                    let _ = last_reply.push_str(&r);
                                    audio.play_chime().await;
                                    // Clear the draft so the next turn starts fresh
                                    // (otherwise the old prompt lingers and re-sends).
                                    kb.set_text("");
                                    // Turn fully complete and the network is idle
                                    // — a safe point to persist the conversation.
                                    persist(&mut flash, &settings, &history);
                                }
                                Err(_) => {
                                    // Failed: drop the user turn so the chat isn't
                                    // wedged, and keep the draft so the user can
                                    // retry. The error is already shown on screen.
                                    let _ = history.pop();
                                }
                            }
                            mode = Mode::ShowingResponse(0);
                            break; // reply is up; don't process stale queued events
                        }
                        Outcome::Expand => {
                            info!("Expand requested; draft len={}", kb.text().len());
                            // Stream a rewrite of the draft, then replace the draft
                            // in place via `Keyboard::set_text` (the M2 improvement).
                            let mut prompt: HString<PROMPT_CAP> = HString::new();
                            let _ = prompt.push_str(EXPAND_PREFIX);
                            let _ = prompt.push_str(kb.text());
                            let rewrite =
                                stream_expand_to_screen(&mut lcd, &mut net, &settings, &prompt)
                                    .await;
                            match rewrite {
                                Ok(r) => {
                                    audio.play_chime().await;
                                    kb.set_text(&r);
                                    // Repaint the keyboard with the rewritten draft.
                                    let _ = Ui::render(&mut lcd, &kb, &status);
                                }
                                Err(_) => {
                                    // Error already shown on screen; keep it up
                                    // until a key, like a normal response view.
                                    last_reply.clear();
                                    mode = Mode::ShowingResponse(0);
                                }
                            }
                            break; // a network turn ran; drop stale queued events
                        }
                    }
                }
                if dirty {
                    audio.play_click().await; // one soft click per visible change
                    let _ = Ui::render(&mut lcd, &kb, &status);
                }
            }
        }

        Timer::after(tick).await;
    }
}

/// Render the settings menu from the current selections.
fn draw_menu<D>(lcd: &mut D, settings: &Settings, history: &[Turn])
where
    D: embedded_graphics::draw_target::DrawTarget<Color = embedded_graphics::pixelcolor::Rgb565>,
{
    let mut model_row: HString<48> = HString::new();
    let _ = write!(model_row, "Model: {}", settings.model());
    let mut persona_row: HString<32> = HString::new();
    let _ = write!(persona_row, "Persona: {}", PERSONAS[settings.persona].0);
    let mut tokens_row: HString<24> = HString::new();
    let _ = write!(tokens_row, "Max tokens: {}", settings.max_tokens());
    let mut newconv_row: HString<32> = HString::new();
    let _ = write!(newconv_row, "New conversation ({})", history.len());

    let mut items: HVec<&str, MENU_ROWS> = HVec::new();
    let _ = items.push(model_row.as_str());
    let _ = items.push(persona_row.as_str());
    let _ = items.push(tokens_row.as_str());
    let _ = items.push(newconv_row.as_str());
    for (name, _) in QUICK_PROMPTS {
        let _ = items.push(name);
    }
    for (label, _, _) in GAMES {
        let _ = items.push(label);
    }
    let _ = items.push("Back");
    let _ = Ui::menu(lcd, "Settings (A/L/D=use/change)", &items, settings.cursor);
}

/// Snapshot the current settings + history into flash. Call ONLY at quiescent
/// points (no network request in flight): after a settings change and after a
/// turn fully completes. Errors are logged and swallowed inside `storage::save`.
fn persist(flash: &mut storage::Flash, settings: &Settings, history: &[Turn]) {
    let mut turns: HVec<(u8, HString<TURN_CAP>), MAX_TURNS> = HVec::new();
    for (role, text) in history {
        let mut s: HString<TURN_CAP> = HString::new();
        let _ = s.push_str(text);
        let _ = turns.push((storage::role_to_u8(*role), s));
    }
    let data = storage::Persisted {
        model: settings.model as u8,
        persona: settings.persona as u8,
        max_tokens: settings.max_tokens as u8,
        turns,
    };
    storage::save(flash, &data);
}

/// Push a turn into the bounded history, truncating its text to `TURN_CAP` bytes
/// (on a char boundary) and dropping the oldest turn(s) when the ring is full.
fn push_turn(history: &mut HVec<Turn, MAX_TURNS>, role: Role, text: &str) {
    let mut stored: HString<TURN_CAP> = HString::new();
    for ch in text.chars() {
        if stored.push(ch).is_err() {
            break; // hit TURN_CAP; keep the prefix that fit
        }
    }
    if history.is_full() {
        history.remove(0);
    }
    let _ = history.push((role, stored));
}

/// Stream a multi-turn chat reply onto the full-screen response view, repainting
/// the tail as each delta arrives. Builds the turn list from `history` (the last
/// turn is the just-pushed user message) and feeds the chosen model / persona /
/// max_tokens from `settings`. Returns `Ok(reply)` on success or `Err(())` after
/// showing an error banner.
///
/// Generic over the draw target so it works with the concrete ST7735 without
/// spelling out its (very long) type. The accumulator + LCD are disjoint from
/// `net`, so the per-delta closure can borrow them while `net` streams.
async fn stream_chat_to_screen<D>(
    lcd: &mut D,
    net: &mut Net,
    settings: &Settings,
    history: &[Turn],
    session_tokens: &mut u32,
) -> Result<HString<RESPONSE_CAP>, ()>
where
    D: embedded_graphics::draw_target::DrawTarget<Color = embedded_graphics::pixelcolor::Rgb565>,
{
    // Build the borrowed (Role, &str) turn slice the core body builder wants.
    let mut turns: HVec<(Role, &str), MAX_TURNS> = HVec::new();
    for (role, text) in history {
        let _ = turns.push((*role, text.as_str()));
    }

    net.set_led(true).await;
    let mut acc: HString<RESPONSE_CAP> = HString::new();

    // Retry a transient connect/TLS failure (Transport) a couple of times — but
    // only while nothing has streamed yet, so we never duplicate partial text.
    const MAX_ATTEMPTS: u8 = 3;
    let mut attempt: u8 = 0;
    let result = loop {
        attempt += 1;
        acc.clear();
        let mut got_delta = false;
        let mut painted_len = 0usize;
        let _ = Ui::response(
            lcd,
            if attempt == 1 { "Streaming..." } else { "Retrying..." },
            "",
        );
        let r = net
            .send_chat(
                settings.model(),
                settings.max_tokens(),
                settings.system(),
                &turns,
                |delta| {
                    got_delta = true;
                    for ch in delta.chars() {
                        if acc.push(ch).is_err() {
                            break;
                        }
                    }
                    // The redraw is a blocking full-screen SPI paint; doing it on
                    // every token starves the WiFi/TCP tasks and drops the stream.
                    // Repaint at most every ~24 new chars; the final paint below
                    // always shows the complete reply.
                    if acc.len() >= painted_len + 24 {
                        painted_len = acc.len();
                        let _ = Ui::response(lcd, "Streaming...", &acc);
                    }
                },
            )
            .await;
        match r {
            Err(NetError::Transport) if !got_delta && attempt < MAX_ATTEMPTS => {
                Timer::after(Duration::from_millis(600)).await;
                continue;
            }
            other => break other,
        }
    };

    net.set_led(false).await;

    match result {
        Ok(reply_tokens) => {
            // Accumulate this reply's tokens into the running session total and
            // show both in the header (reply this turn / running sum).
            *session_tokens = session_tokens.saturating_add(reply_tokens);
            let mut hdr: HString<32> = HString::new();
            // Prefer the spaced form; fall back to a compact one if it would be
            // too wide for the header row.
            let _ = write!(hdr, "{}t  sum {}t  L=back", reply_tokens, *session_tokens);
            if hdr.len() > 26 {
                hdr.clear();
                let _ = write!(hdr, "{}t/{}t  L=back", reply_tokens, *session_tokens);
            }
            let _ = Ui::response(lcd, &hdr, &acc);
            Ok(acc)
        }
        Err(e) => {
            let mut hdr: HString<32> = HString::new();
            let _ = write!(hdr, "Error: {:?}", e);
            let _ = Ui::response(lcd, &hdr, &acc);
            Err(())
        }
    }
}

/// Stream an Expand rewrite (single-turn, no history). On success returns the
/// rewritten draft text for the caller to install via `Keyboard::set_text`; on
/// failure shows an error banner and returns `Err(())`.
async fn stream_expand_to_screen<D>(
    lcd: &mut D,
    net: &mut Net,
    settings: &Settings,
    prompt: &str,
) -> Result<HString<RESPONSE_CAP>, ()>
where
    D: embedded_graphics::draw_target::DrawTarget<Color = embedded_graphics::pixelcolor::Rgb565>,
{
    let mut acc: HString<RESPONSE_CAP> = HString::new();
    let _ = Ui::response(lcd, "Rewriting...", "");
    net.set_led(true).await;

    let result = net
        .send_chat(
            settings.model(),
            settings.max_tokens(),
            settings.system(),
            &[(Role::User, prompt)],
            |delta| {
                for ch in delta.chars() {
                    if acc.push(ch).is_err() {
                        break;
                    }
                }
                let _ = Ui::response(lcd, "Rewriting...", &acc);
            },
        )
        .await;

    net.set_led(false).await;

    match result {
        // Expand's header stays as-is; the token count is unused here.
        Ok(_) => Ok(acc),
        Err(e) => {
            let mut hdr: HString<32> = HString::new();
            let _ = write!(hdr, "Error: {:?}", e);
            let _ = Ui::response(lcd, &hdr, &acc);
            Err(())
        }
    }
}
